### ISSUE TITLE
Tell me how to use

### ISSUE THREAD

**Issue by FullZero5** [PebbleRoad/mithril.paginate#1]
Hi, could you show me how to use your plugin? Code in the sandbox
[jsfiddle.net](https://jsfiddle.net/80rvnyrs/7/)
Thank you

**Comment by rmdort** [comment]
If you read carefully, there is a "how to use" section in the description . And if u know mithril, you can create a demo on jsfiddle

**Comment by FullZero5** [comment]
Ok, thank you, close issue
